// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anomalies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnomaliesByEvent = `-- name: GetAnomaliesByEvent :many
SELECT id,
       user_id,
       event_id,
       anomaly_type,
       score,
       details,
       detected_at
FROM anomalies
WHERE event_id = $1
`

func (q *Queries) GetAnomaliesByEvent(ctx context.Context, eventID pgtype.Int8) ([]Anomaly, error) {
	rows, err := q.db.Query(ctx, getAnomaliesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anomaly
	for rows.Next() {
		var i Anomaly
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.AnomalyType,
			&i.Score,
			&i.Details,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnomaliesByUser = `-- name: GetAnomaliesByUser :many
SELECT id,
       user_id,
       event_id,
       anomaly_type,
       score,
       details,
       detected_at
FROM anomalies
WHERE user_id = $1
ORDER BY detected_at DESC
LIMIT $2
`

type GetAnomaliesByUserParams struct {
	UserID int32
	Limit  int32
}

func (q *Queries) GetAnomaliesByUser(ctx context.Context, arg GetAnomaliesByUserParams) ([]Anomaly, error) {
	rows, err := q.db.Query(ctx, getAnomaliesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anomaly
	for rows.Next() {
		var i Anomaly
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.AnomalyType,
			&i.Score,
			&i.Details,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnomaly = `-- name: InsertAnomaly :one
INSERT INTO anomalies (
    user_id,
    event_id,
    anomaly_type,
    score,
    details,
    detected_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertAnomalyParams struct {
	UserID      int32
	EventID     pgtype.Int8
	AnomalyType string
	Score       pgtype.Float8
	Details     []byte
	DetectedAt  pgtype.Timestamptz
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAnomaly,
		arg.UserID,
		arg.EventID,
		arg.AnomalyType,
		arg.Score,
		arg.Details,
		arg.DetectedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
