// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldEvents = `-- name: DeleteOldEvents :exec
DELETE FROM events
WHERE timestamp < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteOldEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldEvents)
	return err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id,
       user_id,
       event_type,
       timestamp,
       ip,
       user_agent,
       country,
       metadata,
       created_at
FROM events
ORDER BY timestamp DESC
LIMIT $1
`

func (q *Queries) GetAllEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, getAllEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.Ip,
			&i.UserAgent,
			&i.Country,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventById = `-- name: GetEventById :one
SELECT id,
       user_id,
       event_type,
       timestamp,
       ip,
       user_agent,
       country,
       metadata,
       created_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventById(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Timestamp,
		&i.Ip,
		&i.UserAgent,
		&i.Country,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getEventsByUser = `-- name: GetEventsByUser :many
SELECT id,
       user_id,
       event_type,
       timestamp,
       ip,
       user_agent,
       country,
       metadata,
       created_at
FROM events
WHERE user_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type GetEventsByUserParams struct {
	UserID int32
	Limit  int32
}

func (q *Queries) GetEventsByUser(ctx context.Context, arg GetEventsByUserParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Timestamp,
			&i.Ip,
			&i.UserAgent,
			&i.Country,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    user_id,
    event_type,
    timestamp,
    ip,
    user_agent,
    country,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertEventParams struct {
	UserID    int32
	EventType string
	Timestamp pgtype.Timestamptz
	Ip        pgtype.Text
	UserAgent pgtype.Text
	Country   pgtype.Text
	Metadata  []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.UserID,
		arg.EventType,
		arg.Timestamp,
		arg.Ip,
		arg.UserAgent,
		arg.Country,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
