// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Anomaly struct {
	ID          int64
	UserID      int32
	EventID     pgtype.Int8
	AnomalyType string
	Score       pgtype.Float8
	Details     []byte
	DetectedAt  pgtype.Timestamptz
}

type Event struct {
	ID        int64
	UserID    int32
	EventType string
	Timestamp pgtype.Timestamptz
	Ip        pgtype.Text
	UserAgent pgtype.Text
	Country   pgtype.Text
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	LastSeen  pgtype.Timestamptz
}
