// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RawEvent struct {
	ID         int64
	UserID     int32
	EventType  string
	Timestamp  pgtype.Timestamptz
	Ip         pgtype.Text
	UserAgent  pgtype.Text
	Country    pgtype.Text
	Metadata   []byte
	Additional []byte
	CreatedAt  pgtype.Timestamptz
	SessionID  pgtype.Text
}

type User struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	LastSeen  pgtype.Timestamptz
}
