// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, last_seen
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.LastSeen)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, created_at, last_seen)
VALUES ($1, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET last_seen = NOW()
RETURNING id
`

func (q *Queries) InsertUser(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, insertUser, id)
	err := row.Scan(&id)
	return id, err
}
